name: template
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations: # Add this line
    sdk: flutter         # Add this line

  cupertino_icons: ^1.0.3
  provider: ^6.0.1
  http: ^0.13.4
  shared_preferences: ^2.0.8
  sembast: ^3.1.1
  sembast_web: '>=1.0.0'
  path_provider: ^2.0.5
  loader_overlay: ^2.0.2+1
  encrypt: ^5.0.1
  url_launcher: ^6.0.12
  connectivity: ^3.0.6
  overlay_support: ^1.2.1
  flutter_map: ^0.14.0
  carousel_slider: ^4.0.0
  persian_datetime_picker: ^2.3.0

#  search_choices: ^2.0.14
#  permission_handler: ^8.1.4+2
#  heatmap_calendar_shamsi:
#    path: ../flutter_heatmap_calendar_shamsi
#  shamsi_date: ^0.16.0
#  package_info: ^2.0.2
#  just_audio: ^0.9.11
#  firebase_core: ^1.4.0
#  firebase_messaging: ^10.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
    
#  change_app_package_name: ^1.0.0
#  flutter_launcher_icons: ^0.9.1
#  flutter_native_splash: ^1.2.0


#-- flutter pub run change_app_package_name:main com.new.package.name

#-- flutter pub run flutter_launcher_icons:main
#flutter_icons:
#  image_path: "assets/logo.png"
#  android: true
#  ios: true
#  remove_alpha_ios: true

#-- flutter pub run flutter_native_splash:create
#flutter_native_splash:
#  image: "assets/splashIcon.png"
#  color: "ffffff"
#  android_disable_fullscreen: true
#  fill: true
#  android: true



# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/weather/
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: IRANSans_bold
      fonts:
        - asset: fonts/IRANSans_bold.ttf
    - family: IRANSans_medium
      fonts:
        - asset: fonts/IRANSans_medium.ttf
    - family: MyIcon
      fonts:
        - asset: fonts/MyIcon.ttf

