/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
///
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';

class MyColors {
  static const Color cyan = Color(0xff0D1E41);
  static const Color cyanLite = Color(0xff304C89);
  static const Color indigo = Color(0xff1D315C);
  static const Color amber = Color(0xffFFBF19);
  static const Color orange = Color(0xffFF3D00);
  static const Color white = Color(0xffFFFFFF);
  static const List<Color> btog = [
    Color(0xff01FFA3),
    Color(0xff0DAC57),
  ];
  static const Color gray = Color(0xffB5B5B5);

  static const Color primary = Color(0xFF1976D2);
  static const Color primaryDark = Color(0xFF1565C0);
  static const Color primaryLight = Color(0xFF1E88E5);
  static const Color accent = Color(0xFFFF4081);
  static const Color accentDark = Color(0xFFF50057);
  static const Color accentLight = Color(0xFFFF80AB);
  static const Color textFieldG = Colors.grey;
  static const Color error = Colors.red;
  static const Color grey_3 = Color(0xFFf7f7f7);
  static const Color grey_5 = Color(0xFFf2f2f2);
  static const Color grey_10 = Color(0xFFe6e6e6);
  static const Color grey_20 = Color(0xFFcccccc);
  static const Color grey_40 = Color(0xFF999999);
  static const Color grey_60 = Color(0xFF666666);
  static const Color grey_80 = Color(0xFF37474F);
  static const Color grey_90 = Color(0xFF263238);
  static const Color grey_95 = Color(0xFF1a1a1a);
  static const Color grey_100_ = Color(0xFF0d0d0d);




}

class MyIcon {
  MyIcon._();

  static const _kFontFam = 'MyIcon';
  static const String? _kFontPkg = null;

  static const IconData user_2 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_3 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData activity = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_user = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow___down_2 = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow___down_3 = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow___down_circle = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow___down_square = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow___down = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow___left_2 = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow___left_3 = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow___left_circle = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow___left_square = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow___left = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow___right_2 = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow___right_3 = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow___right_circle = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow___right_square = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow___right = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow___up_2 = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow___up_3 = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow___up_circle = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow___up_square = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow___up = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bag_2 = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bag = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData buy = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call_missed = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call_silent = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calling = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData category = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close_square = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData danger = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData discount = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData discovery = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_square = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter_2 = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData game = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData graph = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hide = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_bold = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image_2 = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_circle = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_square = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData login = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_circle = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_square = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper_download = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper_fail = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper_negative = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper_plus = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper_upload = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData password = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scan = IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send = IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData setting_bold = IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData setting = IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield_done = IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield_fail = IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData show = IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData swap = IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tick_square = IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ticket_star = IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ticket = IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData time_circle = IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData time_square = IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unlock = IconData(0xe85d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload = IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video = IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData voice_2 = IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData voice = IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_down = IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_off = IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_up = IconData(0xe864, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet = IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData work = IconData(0xe866, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_up_1 = IconData(0xe867, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData windy_rain_inv = IconData(0xe868, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snow_inv = IconData(0xe869, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snow_heavy_inv = IconData(0xe86a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hail_inv = IconData(0xe86b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clouds_inv = IconData(0xe86c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clouds_flash_inv = IconData(0xe86d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData temperature = IconData(0xe86e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compass = IconData(0xe86f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData na = IconData(0xe870, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData celcius = IconData(0xe871, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fahrenheit = IconData(0xe872, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clouds_flash_alt = IconData(0xe873, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sun_inv = IconData(0xe874, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon_inv = IconData(0xe875, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_sun_inv = IconData(0xe876, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_moon_inv = IconData(0xe877, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_inv = IconData(0xe878, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_flash_inv = IconData(0xe879, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drizzle_inv = IconData(0xe87a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rain_inv = IconData(0xe87b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData windy_inv = IconData(0xe87c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sunrise = IconData(0xe87d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sun = IconData(0xe87e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon = IconData(0xe87f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eclipse = IconData(0xe880, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mist = IconData(0xe881, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wind = IconData(0xe882, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snowflake = IconData(0xe883, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_sun = IconData(0xe884, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_moon = IconData(0xe885, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fog_sun = IconData(0xe886, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fog_moon = IconData(0xe887, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fog_cloud = IconData(0xe888, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fog = IconData(0xe889, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud = IconData(0xe88a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_flash = IconData(0xe88b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_flash_alt = IconData(0xe88c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drizzle = IconData(0xe88d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rain = IconData(0xe88e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData windy = IconData(0xe88f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData windy_rain = IconData(0xe890, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snow = IconData(0xe891, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snow_alt = IconData(0xe892, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snow_heavy = IconData(0xe893, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hail = IconData(0xe894, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clouds = IconData(0xe895, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clouds_flash = IconData(0xe896, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signal_cellular_no_sim = IconData(0xe897, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gps_icon3 = IconData(0xe898, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sim_card_alert = IconData(0xe899, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_full = IconData(0xf240, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_three_quarters = IconData(0xf241, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_half = IconData(0xf242, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_quarter = IconData(0xf243, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_empty = IconData(0xf244, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exchange_alt = IconData(0xf362, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shipping_fast = IconData(0xf48b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car_battery = IconData(0xf5df, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car_crash = IconData(0xf5e1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sim_card_1 = IconData(0xf7c4, fontFamily: _kFontFam, fontPackage: _kFontPkg);


}
